#! /bin/sh

#####################
#  Keyboard layout  #
#####################

# Swp Caps Lock with Right Control
setxkbmap -layout us -variant altgr-intl -option ctrl:nocaps



##############################
#  Setup Monitors / Screens  #
##############################

# Todo: Check the actual name of the monitor (DP-1?)
xrandr --query | grep -qe '^DP-1 connected'
if [[ $? -eq 0 ]] ; then
	# Halma office
	xrandr \
		# Todo: Check actual resolution of monitor!!
		--output DP-1 --primary --mode 2560x1440 --rotate normal \
		--output eDP-1 --mode --rotate normal --left-of DP-2-1
else
	#Home office
	xrandr \
		--output DP-2-2 --primary --mode 1920x1080 --rotate normal \
		--output DP-2-1 --mode 1920x1080 --rotate normal --right-of DP-2-2 \
		--output eDP-1 --rotate normal --left-of DP-2-2
fi



sxhkd &	 		# Keybindings
polybar &		# Run Polybar
compton & 		# Add transparency


###############
#  Wallpaper  #
###############

feh --bg-tile ${HOME}/dotfiles/themer-one/wallpaper-octagon/themer-wallpaper-octagon-dark-2880x1800.png



bspc monitor DVI-D-1 -d 1 2 3 4 5
bspc monitor DP-2-2 -d 1 2 3 4 5
# bspc monitor DVI-I-1 -d 6 7 8 9 10


bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config automatic_scheme 	longest_side
