#! /bin/sh

# Keyboard layout
# Swp Caps Lock with Right Control
setxkbmap -layout us -variant altgr-intl -option ctrl:nocaps

sxhkd &	 		# Keybindings
polybar &		# Run Polybar
compton & 		# Add transparency

feh --bg-tile ${HOME}/dotfiles/themer-one/wallpaper-octagon/themer-wallpaper-octagon-dark-2880x1800.png

bspc monitor DVI-D-1 -d 1 2 3 4 5
# bspc monitor DVI-I-1 -d 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config automatic_scheme 	spiral

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


