#! /bin/sh

# Keyboard layout
# Swp Caps Lock with Right Control
setxkbmap -layout us -variant altgr-intl -option ctrl:nocaps

sxhkd &	 		# Keybindings
polybar &		# Run Polybar
compton & 		# Add transparency

nitrogen --set-tiled /home/hannenz/emmas_cats_1920x1080.jpg

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d DVI-D-1 I II III IV
bspc monitor -d DVI-I-1 -d V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config automatic_scheme 	spiral

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


